name: run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install "beautifulsoup4==4.9.1"
          python -m pip install "dateparser==0.7.6"
          python -m pip install "requests==2.24.0"
          python -m pip install "feedparser==6.0.8"
          python -m pip install --no-deps pygooglenews
          python -m pip install lxml_html_clean
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
