name: Fetch and Upsert News

on:
  schedule:
    - cron: '0 * * * *' # Every hour at minute 0
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: install python packages pygooglenews
        run: |
          python -m pip install --upgrade pip
          python -m pip install "beautifulsoup4==4.9.1"
          python -m pip install "dateparser==0.7.6"
          python -m pip install "requests==2.24.0"
          python -m pip install "feedparser==6.0.8"
          python -m pip install --no-deps pygooglenews
          python -m pip install lxml_html_clean


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            

      - name: Run fetch_and_upsert_by_topic
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python fetch_and_upsert_by_topic.py


